[phases.setup]
nixPkgs = ['jdk17']

[phases.build]
cmds = ['./gradlew clean bootJar -x test']

[start]
cmd = 'java -Dserver.port=$PORT $JAVA_OPTS -jar build/libs/InmoMarketBackEnd-0.0.1-SNAPSHOT.jar'
